name: Terraform checks

on:
  pull_request:
  push:
    branches: [ main ]
permissions: read-all

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # -----------------------------
    # Terraform
    # -----------------------------
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3
        terraform_wrapper: false
    # Formatting consistency
    - name: Terraform format check
      run: terraform fmt -check -recursive

    # Syntax & provider correctness
    - name: Terraform validate
      run: |
        find . -type f -name "*.tf" -not -path "./modules/*" -print0 \
        | xargs -0 -n1 dirname \
        | sort -u \
        | while read dir; do
            echo "Validating $dir"
            terraform -chdir="$dir" init -backend=false -input=false
            terraform -chdir="$dir" validate
          done

    # -----------------------------
    # TFLint
    # -----------------------------
    #Terraform & provider best practices
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: TFLint
      run: |
        tflint --init
        tflint --recursive

    # -----------------------------
    # Checkov (IaC security scanning)
    # -----------------------------
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        quiet: true
        framework: terraform

    # -----------------------------
    # Secret scanning
    # -----------------------------
    - name: Install Gitleaks
      run: |
        sudo apt-get update
        sudo apt-get install -y gitleaks

    - name: Run Gitleaks
      run: |
        gitleaks detect \
        --source . \
        --no-git \
        --redact \
        --report-format sarif \
        --report-path /tmp/gitleaks.sarif

    # -----------------------------
    # Publish SARIF results
    # -----------------------------
    - name: Upload Gitleaks SARIF
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        sarif_file: /tmp/gitleaks.sarif
